---
- name: Enable delegation to on {{ target_computer }} 
  ansible.windows.win_powershell:
    script: |
      Set-ADComputer -Identity {{ target_computer }} -Add @{'msDS-AllowedToDelegateTo'='{{ spn }}'}
  loop: '{{ delegation_spns }}'
  loop_control:
    loop_var: spn
